// Generated by LiveScript 1.3.1
(function(){
  var TodoApp;
  TodoApp = React.createClass({displayName: "TodoApp",
    render: function(){
      return React.createElement("div", null, "Hello world");
    }
  });
  React.render(React.createElement(TodoApp, null), document.getElementById("todo_app"));
}).call(this);
